name: tekartik_web_socket_io
description: Platform io
version: 0.2.2
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.9.0

dependencies:
  tekartik_web_socket:
    git:
      url: https://github.com/tekartik/web_socket.dart
      path: web_socket
      ref: dart3a
    version: '>=0.2.2'
  shelf: '>=0.7.3'
  shelf_web_socket: '>=0.2.2'
  web_socket_channel:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  collection: ">=1.18.0"
  path: ">=1.9.0"
  process_run: ">=1.2.1+1"
  tekartik_web_socket_test:
    git:
      url: https://github.com/tekartik/web_socket.dart
      path: web_socket_test
      ref: dart3a
    version: '>=0.1.0'


resolution: workspace
